import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import "@mantine/core/styles.css";
import '@mantine/charts/styles.css';
import { createTheme, MantineProvider } from "@mantine/core";
import LoadingBackdrop from "./components/ui/LoadingBackdrop";
import { QueryClientProvider } from "@tanstack/react-query";
import queryClient from "./lib/queryClient";
import ToastProvider from "./lib/toaster";

const theme = createTheme({
  cursorType: "pointer",
});

const plusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "InspectBuddy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${plusJakartaSans.variable}`}>
        <QueryClientProvider client={queryClient}>
          <MantineProvider theme={theme}>
            {children}
            <ToastProvider />
            <LoadingBackdrop />
          </MantineProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
